### PR TITLE
Adding contribution manual.

### PR DESCRIPTION
**Pull request by jamalv**
## Todo:
- [x] add mark-down style guide
- [ ] review if 2b is correct @maxvisser

@maxvisser, I have some trouble with 2b: creating a new document. As far as my understanding goes, it means that https://github.com/teamforus/docs.forus.io/blob/master/_data/toc.yml needs to be updated. Since this file is in another repo, this might cause some confusion. 

Is there a more user-friendly way of going about this? Maybe with placing the file toc.yml in the docs repo instead of in docs.forus.io and then creating a pointer to it in docs.forus.io? toc.yml could then be in the root of docs and even get a more descriptive name (e.g. navigation-structure).

**Side note:** can we remove _config.yml from docs?

### CODE REVIEW

**Comment by maxvisser** [comment]
Yes, _config.yml can be deleted

**Comment by maxvisser** [comment]
adding the whole _data folder to docs would be a bit of a mess structure wise but should be possible.

**Comment by jamalv** [comment]
Looking what _data contains, I think it would make sense. It would make /docs more self-contained.

I don't think _data is a very descriptive name though (in /docs), maybe _menu-settings is better?

**Comment by maxvisser** [comment]
I made a seperate pull request https://github.com/teamforus/docs/pull/20 for your feature request to test if this would work. Can you review and merge it?

**Comment by jamalv** [comment]
Done

**Comment by maxvisser** [comment]
It works but not how we wanted it to work. the _data folder is mandatory therefore i created a splitted subtree to menu_settings in this repository to make it work.

So I think we need to write a deploy script for deploying changes to this repository to docs.forus.io.

**Pull request merged**
